In [1]:
import numpy as np
import scipy

print(np.__version__)

2.3.3


In [5]:
x = np.array([[1,2,3],[1,4,5]])
print("x:\n{}".format(x))

x:
[[1 2 3]
 [1 4 5]]


In [8]:
from scipy import sparse
eye =  np.eye(4)
print("eye:\n {}".format(eye))

eye:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
sparse_matrix = sparse.csr_matrix(eye)
print("sparse matrix:\n{}".format(sparse_matrix))

sparse matrix:
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4 stored elements and shape (4, 4)>
  Coords	Values
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [16]:
## creating a sparse matrix using the COO method
data = np.ones(4)
row_indices = np.arange(4)
column_indices = np.arange(4)
eye_coo = sparse.coo_matrix((data, (row_indices, column_indices)))
print("COO representation: \n {}".format(eye_coo))

COO representation: 
 <COOrdinate sparse matrix of dtype 'float64'
	with 4 stored elements and shape (4, 4)>
  Coords	Values
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
