# The weather and play problem

In [16]:
weather = [
    "Sunny", "Sunny", "Overcast", "Rainy", "Rainy", "Rainy",
    "Overcast", "Sunny", "Sunny", "Rainy", "Sunny",
    "Overcast", "Overcast", "Rainy"
]
play = [
    "No", "No", "Yes", "Yes", "Yes", "No",
    "Yes", "Yes", "Yes", "No", "Yes",
    "Yes", "Yes", "No"
]

In [17]:
from sklearn import preprocessing
encoder = preprocessing.LabelEncoder()
weather_encoded = encoder.fit_transform(weather)


In [18]:
label = encoder.fit_transform(play)

In [19]:
label

array([0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0])

In [20]:
weather_encoded

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])

In [21]:
import numpy as np
weather_encoded = np.reshape(weather_encoded, (-1, 1))

In [22]:
weather_encoded

array([[2],
       [2],
       [0],
       [1],
       [1],
       [1],
       [0],
       [2],
       [2],
       [1],
       [2],
       [0],
       [0],
       [1]])

In [23]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB().fit(weather_encoded, label)

In [24]:
clf.predict([[0]])

array([1])

## Naive Bayes classification used on the Breast cancer dataset

In [25]:
from sklearn.datasets import load_breast_cancer
breast_cancer_ds = load_breast_cancer()

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(breast_cancer_ds.data, breast_cancer_ds.target, random_state=42)

In [27]:
breast_cancer_clf = GaussianNB().fit(X_train, y_train)

In [28]:
print(f"Training accuracy:{breast_cancer_clf.score(X_train, y_train)}")
print(f"Test accuracy: {breast_cancer_clf.score(X_test, y_test)}")

Training accuracy:0.9366197183098591
Test accuracy: 0.958041958041958


# Feature Scaling

In [29]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

breast_cancer_clf = GaussianNB().fit(X_train, y_train)

In [30]:
print(f"Training accuracy:{breast_cancer_clf.score(X_train, y_train)}")
print(f"Test accuracy: {breast_cancer_clf.score(X_test, y_test)}")

Training accuracy:0.9366197183098591
Test accuracy: 0.951048951048951
